name: Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Newman and Reporters
        run: npm install newman newman-reporter-htmlextra newman-reporter-allure

      - name: Run API Tests
        run: npx newman run "TMDB_API_Tests.postman_collection.json" --environment TMDB.postman_environment.json --env-var "api_key=${{ secrets.TMDB_API_KEY }}" --env-var "base_url=https://api.themoviedb.org/3" --reporters cli,htmlextra,allure --reporter-htmlextra-export reports/test-report.html --reporter-allure-resultsDir allure-results

      - name: Check Allure Results
        run: ls -la allure-results || echo "allure-results folder not found"
        if: always()
      
      - name: Run API Mock Tests
        run: npx newman run "TMDB_API_Tests_Mock_Server.postman_collection.json" --environment TMDB_Mock_Server.postman_environment.json --env-var "api_key=${{ secrets.TMDB_API_KEY }}" --env-var "base_url=https://6cd6cc6f-9516-431b-bebb-a37a90e7421f.mock.pstmn.io" --reporters cli,htmlextra,allure --reporter-htmlextra-export reports/test-report-mock.html --reporter-allure-resultsDir allure-results-mock

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
  
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report
        if: always()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
 